---
apiVersion: v1           # from kubernetes.io/docs
kind: ResourceQuota      # kubernetes resource to be created
metadata:
  name: prod-resourcequota  # name of ResourceQuota
spec:
  hard:                  # "may not exceed"
    cpu: "2"             # 1 cpu is == 1 vcore on a hypervisor or 1 hyperthread on bare metal
    memory: 2Gi          # 2 gigs of memory
